Updated docs for Products and plans and san-tokens pages
santiment/academy pull request #307
Opened 2023-05-18 08:37 UTC by borisvuchkov

## Changes

## Checklist

- [ ] My article available in Navigation sidebar and in root article of selected category ([how to do it in README](https://github.com/santiment/academy#add-an-article-into-navigation-sidebar))
- [ ]	My article have [metadata](https://github.com/santiment/academy#metadata) (title, description, date when updated and author)
- [ ]	All added/updated links in article are exist, images shows correctly

2023-05-19 13:06 UTC, tzanko-matev requested changes
* The articles `access-plans/sanapi.md`, `access-plans/sanbase.md` and `access-plans/special-restrictions.md` are not shown on the left-side navigation panel. I don't know why that is, maybe the navigation panel does not support three levels of nesting. This issue should be fixed - if third level nesting is not possible then we should move those articles to the parent folder and include them in the navigation

* See the other issues in the other comments

2023-05-19 13:06 UTC, tzanko-matev commented on src/docs/san-tokens/how-to-buy-san-tokens/index.md
> +In summary, decentralized exchanges offer a more secure and private way to trade cryptocurrencies compared to centralized exchanges. However, they may require a bit more technical knowledge to naviga
Those paragraphs were not in the previous version. I wonder do we need so much text to describe a DEX here? Does this provide value to the reader?

2023-09-07 09:36 UTC, alexander-gr approved these changes

2023-09-28 02:57 UTC, tzanko-matev approved these changes

2023-10-13 08:08 UTC, merged